### ISSUE TITLE
Disable Access time modification 

### ISSUE THREAD

**Issue by piyush-kurur** [navya/mirror.cse.iitk.ac.in#2]
You might want to disable access time updates on the file system that contains the mirror data for better performance. I cannot think of any adverse implication of this change.

**Comment by adarshaj** [comment]
:+1: 
Done, I've updated `/etc/fstab` with `noatime,nodiratime` for the mirror-root's mount entry.

I've enabled some additional optimizations in no. of max sockets and kernel buffers for optimizing serving static files from nginx.
