### ISSUE TITLE
mirror.cse seems inaccessible

### ISSUE THREAD

**Issue by piyush-kurur** [navya/mirror.cse.iitk.ac.in#4]
While updating my debian repository here, I noticed that the machine mirror.cse seems inaccessible from  IIT Palakkad `iitpkd.ac.in` ? Can some one check it ?

**Comment by yashsriv** [comment]
Hi, so the cse network infrastructure has undergone some changes recently. All *.cse.iitk.ac.in were down even from inside campus a few days ago. Maybe that is the reason.

The mirrors are accessible from within campus right now but even I can't access from an external machine. I'll try making a ticket on kendra.

**Comment by piyush-kurur** [comment]
This ticket was fixed some months ago but now the issue seems to have resurfaced. I am not able to access
mirror.cse. from IIT Palakkad.

**Comment by adarshaj** [comment]
I can confirm the issue, but unfortunately, I don't seem to be in position to fix it as I don't know the internal NAT mapping. I'll forward issue to lab staff for getting a permanent fix in place!

**Comment by piyush-kurur** [comment]
Can we have a status checking service like http://uptimerobot.com enabled for mirror ? Another option is to (mis)-use travis to do periodic checks and automatically inform on the irc channel. This has the advantage that one can actually configure the checking script.

**Comment by ford-prefect** [comment]
I have some spare slots on my Apex Ping account. Can set this up if you give me an email to send downtime notifications to.

**Comment by piyush-kurur** [comment]
@ford-prefect Can it raise tickets on github automatically ? That would be great actually if it can do that.
At the very least it should send a message to the navya@freenode.

**Comment by adarshaj** [comment]
This was fixed earlier today.

As per the lab staff: 
> CC had disabled the NATing due to heavy usage. now they have enabled but after applying limit.. 

Not sure if we will be able to host mirror in reliable manner for long term with such support from CC at infra level.
